cluster_users:
    - name: ENC[AES256_GCM,data:0K4MGMq1,iv:03siq1nlqTtAG+2j80pREjdHb7obbRRNCzV5MsJDpJw=,tag:jIh2NIHQvJZ+hrL9Yt3D1A==,type:str]
      role: ENC[AES256_GCM,data:FI3hPd7/UBDsw8cKhQ==,iv:vUmOFqKpaA3/RafvuPm2/wVFfJb88TlM+EcwYA3z9XQ=,tag:1OLVTWoPWgb7wTw62PGfMw==,type:str]
    - name: ENC[AES256_GCM,data:aWdXjBw/f0k=,iv:pYbexHp5cNjJGvH1Osopp8B85ltpEf9bHbTOUJ0sq6c=,tag:XAjEwvDmu0J5C1LDgTCq4A==,type:str]
      role: ENC[AES256_GCM,data:TjUdHiqPumM=,iv:eGbecPNxM65Anv2m/4AmGG74qqAqAiLrHBYwaSp/kJk=,tag:v9NNiWXuAys9Pit2fG2ZHg==,type:str]
      namespaces:
        - ENC[AES256_GCM,data:dhVgDnh8WNU/E/nDaw==,iv:Rw+S/7UDPy/rQTWOb0JEnb3DnvHuIE0ojvCb4CN6tOA=,tag:rtGW9tPIWGOAUvP5Z4oTkA==,type:str]
coin_server:
    auth:
        salt: ENC[AES256_GCM,data:hXzYbLNGNWdVyfTXE7Tr8u2w,iv:8d3lLAfpt/659UZYKZ/2hdeqylxE/tPvTvvdKjsBu98=,tag:KuhIw77XZKkA/twCE/rVXA==,type:str]
        key: ENC[AES256_GCM,data:7gPiwMl7i35tNbdNv85AKvZql8o+rGVL9pbSdJog5g==,iv:wN4e0HqPSJX6LBW1EWeScZxSPEC5LkXNl1Et+LryRz0=,tag:zSV+PE2tY3r1+H9QPvFmaw==,type:str]
    telegram_bot:
        token: ENC[AES256_GCM,data:fW+XlFDVjtlFmawr4rrP4fB5VmYFYITdiTxg4O59sPWhtDrEqfVeGE6WQMr7+A==,iv:aSjzc6NGWdHl304sJfIbh0Zt9AqHJ89gDzx57vDjx2Y=,tag:I1QZaT+eRTPpx3BCEKz1Aw==,type:str]
        chat_id: ENC[AES256_GCM,data:G/oXW5QAPm3aQqtQrl4=,iv:TVmaThEwxnHR+hz4evhYNNGxXgBAaDrdb8okf9QK6RU=,tag:RpluorE34hnpdXyleGpSgQ==,type:str]
    api_key_currency_provider: ENC[AES256_GCM,data:KBCBHmCb2qRwAcQnrNohDg2EUjdRGdfsLjGnIAkcBNbSHPdpTcyF2g==,iv:mocDJsK415Eoy7inrkKV+Nzb5PSxJbJMyN3mNvTxxo4=,tag:KBTg5pxCbi9wI2H1QDXQQQ==,type:str]
    apns:
        team_id: ENC[AES256_GCM,data:rGsQspNfXBJO3g==,iv:XF0aXxU5Bc0/f2UQutRmCpjyz9/zXJfNnih1/Hj7dE8=,tag:SfmaCr3kot7ohp8PeINoxA==,type:str]
        key_id: ENC[AES256_GCM,data:c0y/vfFlwbJrWw==,iv:a0mkgaMn+8qHOoFMrKiGIFaxlGnk/7Ch+yl+Suf+0h4=,tag:1dE9/AuIrkABG0BwQzpM3w==,type:str]
    host: ENC[AES256_GCM,data:EOmLuFquHSw8bNS+bHgZ,iv:EnzbJ77YWVjz0yqdo7Xwr+EsonixhOMT60MDoijfQrk=,tag:hZz5o9hEkynSb0eq0Sk7LQ==,type:str]
pgsql:
    users:
        coin:
            password: ENC[AES256_GCM,data:J8q08ZeMzDVk9ejcu0VTfX/pwHE=,iv:B8qXk0YOwNZGvuzt5YNP9g0gfgRiki6bdJ9s5cgjt9A=,tag:OKhGv95Cc17a+GPaNztGoA==,type:str]
        postgres:
            password: ENC[AES256_GCM,data:1ng6FlGVYSbNmyiIdLmswkKLALI=,iv:sgBHo2f6ohnEX7woO4uynhKGcInx5xIPiYrAavdgvsI=,tag:V1VY34UibBL4Gwcng97U+g==,type:str]
        grafana:
            password: ENC[AES256_GCM,data:9wFePZXMVQPTSCDGxTDeV91vD90=,iv:pMDZ84JKgv9cnxt01VkflQCnO2ZdNdu5hFfO39DsmU0=,tag:BxiJh9WwQBZjVLeemG7dCA==,type:str]
image_credentials:
    registry: ENC[AES256_GCM,data:GQbiOj59rw==,iv:Z3xPpp0JFM4mgI+/1r+fV8ubogleWb5xylwEgM5kzVo=,tag:onRVIxV4x3JoepGKapzDLA==,type:str]
    username: ENC[AES256_GCM,data:tHNRN0hw,iv:vOKMp+BrQqAriSaPc8qcdDqjms5XNhIOjbDJIAonv2U=,tag:H9oxu2cmKoMmmt4k8r3q+A==,type:str]
    password: ENC[AES256_GCM,data:j7QZuKJWr0SdxZquO4npR3UknjCgWFW5prmHrup0MhFY2xbL5vDfQg==,iv:y/aEhQh3TNiCtl+2F+HTxH05/KR5XgdFpzBrIlhrvR8=,tag:QTqysVr5sEVTyppgPWxM0g==,type:str]
grafana:
    adminPassword: ENC[AES256_GCM,data:q7o1oAvrvqhuLL0LwcD+0vnTb4c=,iv:ZdZ98KceXZx54CMcx4sjrCME3D0Puev/ZFVNEak44/I=,tag:tXZyHnBgDqWqe+QjkoJVuA==,type:str]
alertmanager:
    telegram_chat_id: ENC[AES256_GCM,data:O9FbIcxbsGlHCumntJA=,iv:F5itpS8IOzwwj3yqnF05zKPGLq2kRZx2cXZZMtN6jCg=,tag:lQJN8oY5GZJmDdQZsXB9fw==,type:int]
    telegram_topic_id: ENC[AES256_GCM,data:aQ==,iv:GyPmFVrsf+Eh4IlUTHFy/nrQlXNotzKtG6Tly2PgFvY=,tag:x7p8STQPm6WqyfvW8ceqxQ==,type:int]
    telegram_token: ENC[AES256_GCM,data:QBLA5qt//xaYvfSQjzP5+T3oMDdJJcEdeDCtz9s1Cggwnp+2M7kJ07DgZc4zFg==,iv:RH8vHMkcAxR9RlPcCZfi0YRgOVa1ITJbafvFZA7J6u0=,tag:T9xSJ6cmIvsOZPbGnAV/gQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6a1cxS3hLVkFvOVhSUDQ5
            SStseGZnQWZGNUZESlllYlpKOEdJUnRUTTA0CjFLWHMvTnBYM2R2VmljajRlN0h2
            TngxMjJHNGpqeURMdXUwb1NRUGZ2OGcKLS0tICtaWXA0eEdQUndPcVVGMTRCRGk2
            d2dGcGlkc0lLNS95QkxXd3dydHZ2Nm8KycBkJ8eQNPMP5QHSe1ZzPYnFpYbJtV3P
            bwpTBC6kkLuRfCv2KPoF951ZIZZ1k+GXEPu9W20JV2wfTQx+QkG45w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l8t7aweckzrjkaxj998n0th5wvp6kmzjpcazt770uupe67cvhscqnpahda
    lastmodified: "2026-08-02T21:46:28Z"
    mac: ENC[AES256_GCM,data:BJwQMijflCnN3W5dwMPpJ2pcqTiSIIkTtEtqVWN/e3MbeLekuROGT/VH+cTkBL38rwdWe7WsErDziJxypyYqnBRkdAq2LYYFxkdNNCq6yNVr9nckiEkh3LIqm7XKqS5VTbKhh9+ZlPTvcW+akmT13i4d/xgAXQ9p6Vm4EnH6vnA=,iv:WpDq1MeFhbywhuLp84E6BLazqtWjqGbwjNmgZn5vGQw=,tag:cdhncktd7kScEDdQdihZzA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
