coin_server:
    auth:
        salt: ENC[AES256_GCM,data:BOquFskbsLhM4qASchW1mLlLqpo=,iv:JfVk2+nLlnenHvxDGSCfw1YGBLSSMS4iwuaXpFRtNKI=,tag:swsYaMSEepfw3fWBQ0pr1g==,type:str]
        key: ENC[AES256_GCM,data:4jc+te7lzUY7Li8DJX5tqNw76Oc=,iv:stK646zm9pBdDPyiTAeMlTDcWmqNL8Its39D/xVhV5o=,tag:CnS1MhUb2/h71bdN5dkbVw==,type:str]
    telegram_bot:
        token: ""
        chat_id: ENC[AES256_GCM,data:yA==,iv:BwBSNsXEPCT2f/O7W2YXJVul3QEMhHBzZNcKNd7KbQk=,tag:Xsw9lGnbek0MFfx+UvqCVQ==,type:str]
    api_key_currency_provider: ENC[AES256_GCM,data:dwcjFbGlDYb2ZkuQS/F+Va+aB2FUdL7k1/eIRo5e+VAYTp82+X7Z6g==,iv:QOIO8w88xP8b7XEZNx6dbKr8Eb3mOjWsONxbrt/XwOM=,tag:Io/Xi4IgGVgmOmt+vDGtZg==,type:str]
    apns:
        team_id: ""
        key_id: ""
    host: ENC[AES256_GCM,data:ibTQS05lzf79eESeMvjW7tcO74xc+Q==,iv:wYrxJWU3SWyD3YQnwQ3K+A5TMxQKzndKUFsF1cxfnC0=,tag:nVPaRWpVhBM258IKjKwpZg==,type:str]
pgsql:
    users:
        coin:
            password: ENC[AES256_GCM,data:N0Zf6qI9pYcY0NKvWrppIDdTwVQ=,iv:V09F2nOeTUo74u3gPAwoBzjMEpTN+MslPMH3lXrmEg8=,tag:h4DJ0qZKnM+gdjGJ7njvqw==,type:str]
        postgres:
            password: ENC[AES256_GCM,data:LpLMUCkrNcwfXU02EOgrmYYQM6U=,iv:cehjzanDX6c/kAqFniSsYoykQkAvIedeV/I6QeWECvk=,tag:M6pign9MCGOrtRuq+tALMw==,type:str]
image_credentials:
    registry: ENC[AES256_GCM,data:FXHRbUaP4w==,iv:u9I7F23V7gNMWsM31rP6QBno5X16c5tvMDP7OoWBhQk=,tag:+PM1d4dlsal4KzqIAA2ybg==,type:str]
    username: ENC[AES256_GCM,data:7h8IE8pb,iv:vs9v6Bn0h3POYfPTHNyFEzmmgBQ9pO6k7YiPc1YEph0=,tag:osGOpyxdkQsLg9fKpFsEKA==,type:str]
    password: ENC[AES256_GCM,data:gHk34IfZobBybuFSQhHw7aLv0FbI1TeK+RK2sIse0gIICNAZ+0s+QA==,iv:ujJFa5jXQPBBTijH20uJEKfIqE5DsjOcHf79Kbt0cgc=,tag:yPy47cGHos0P+3Waw33YJQ==,type:str]
sops:
    age:
        - recipient: age1l8t7aweckzrjkaxj998n0th5wvp6kmzjpcazt770uupe67cvhscqnpahda
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6a1cxS3hLVkFvOVhSUDQ5
            SStseGZnQWZGNUZESlllYlpKOEdJUnRUTTA0CjFLWHMvTnBYM2R2VmljajRlN0h2
            TngxMjJHNGpqeURMdXUwb1NRUGZ2OGcKLS0tICtaWXA0eEdQUndPcVVGMTRCRGk2
            d2dGcGlkc0lLNS95QkxXd3dydHZ2Nm8KycBkJ8eQNPMP5QHSe1ZzPYnFpYbJtV3P
            bwpTBC6kkLuRfCv2KPoF951ZIZZ1k+GXEPu9W20JV2wfTQx+QkG45w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T13:22:37Z"
    mac: ENC[AES256_GCM,data:FYhnxlknUMc6OmH+D9uaVT4CdyUqawNCydok6jHE20ILWvJ3xwglll7jtaPzS0HEvuLbKUheCDchzG90SZ/jTq+gw8UgSpI30BpNDp4bvUrWvT2Z6v/2P+Iu8GniLDtlxLKBt4tmqzya5+FuCxEp5hMZ6PSUa1KQeFnzxRChk4Y=,iv:LLK2kY0zzqD080i7HDv2fFM20f3YtPkWd90wpT6FRgU=,tag:mF3rGj9pX31r65QyDFU5Hg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
