edit-secrets-coin-1:
	EDITOR="goland --wait" ansible-vault edit coin-1/secrets.yml --vault-password-file ../config/.vault_password

edit-secrets-coin-2:
	EDITOR="goland --wait" ansible-vault edit coin-2/secrets.yml --vault-password-file ../config/.vault_password
