apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  PGSQL_HOST: "{{ .Values.pgsql.endpoint }}"
  OTLP_IS_ENABLED: "{{ .Values.otlp.enabled }}"
  OTLP_HTTP_ENDPOINT: "{{ .Values.otlp.endpoint }}"
  OTLP_INSECURE: "{{ .Values.otlp.insecure}}"
  SERVICE_NAME: "{{ .Values.service_name}}"
  ENVIRONMENT: "{{ .Values.env }}"
  TG_BOT_ENABLED: "{{ .Values.tg_bot.enabled }}"
  STACK_TRACE_ENABLED: "{{ .Values.stack_trace_enabled }}"
  LOG_LEVEL: "{{ .Values.log.level }}"
  LOG_FORMAT: "{{ .Values.log.format }}"
  LISTEN_HTTP: "{{ .Values.listen.http }}"
  LISTEN_GRPC: "{{ .Values.listen.grpc }}"
  PORT_HTTP: "{{ .Values.listen.http }}"
  PORT_GRPC: "{{ .Values.listen.grpc }}"
  AUTH_REFRESH_TOKEN_TTL: "{{ .Values.auth.refresh_token_ttl }}"
  AUTH_ACCESS_TOKEN_TTL: "{{ .Values.auth.access_token_ttl }}"
  NOTIFICATIONS_ENABLED: "{{ .Values.apns.enabled }}"
  NOTIFICATIONS_APNS_KEY_FILE_PATH: "{{ .Values.apns.apns_key_file_path }}"
