postgresql:
    auth:
        password: ENC[AES256_GCM,data:59qTceqZfcjhbcZcJ5Rjc6M4B6A=,iv:PCl4FCVQA4W3pxgmrb+Os8+hZFr5te0X8XbWJN7We2s=,tag:vs3KybYhumbwfdSGPglkgQ==,type:str]
        username: ENC[AES256_GCM,data:Wk9fVA==,iv:xqbAmgvvQRmi3GCO9q/9Ue6YbEMeWPKmXGfJcR1MABQ=,tag:/Hga/v3nz4T151hBVbW3nw==,type:str]
        database: ENC[AES256_GCM,data:0bci2w==,iv:cX+v6Gb16phUGrR7i8fzEv40u+tcA3s9Vd1xyKgB5Zg=,tag:KsxIMUssr9c+a3RRID2PxQ==,type:str]
        postgresPassword: ENC[AES256_GCM,data:NwLJfYLJMO6JlK2XQtsQuzFhoQY=,iv:2D8B61f98YHq0MpdKQ4X5EY6y7mqh06nCZeSng2gPGs=,tag:1VxmzXDByQMRA0gAgvKg/w==,type:str]
coin_server:
    auth:
        salt: ENC[AES256_GCM,data:BOquFskbsLhM4qASchW1mLlLqpo=,iv:JfVk2+nLlnenHvxDGSCfw1YGBLSSMS4iwuaXpFRtNKI=,tag:swsYaMSEepfw3fWBQ0pr1g==,type:str]
        key: ENC[AES256_GCM,data:4jc+te7lzUY7Li8DJX5tqNw76Oc=,iv:stK646zm9pBdDPyiTAeMlTDcWmqNL8Its39D/xVhV5o=,tag:CnS1MhUb2/h71bdN5dkbVw==,type:str]
    telegram_bot:
        token: ""
        chat_id: ENC[AES256_GCM,data:yA==,iv:BwBSNsXEPCT2f/O7W2YXJVul3QEMhHBzZNcKNd7KbQk=,tag:Xsw9lGnbek0MFfx+UvqCVQ==,type:str]
    api_key_currency_provider: ENC[AES256_GCM,data:dwcjFbGlDYb2ZkuQS/F+Va+aB2FUdL7k1/eIRo5e+VAYTp82+X7Z6g==,iv:QOIO8w88xP8b7XEZNx6dbKr8Eb3mOjWsONxbrt/XwOM=,tag:Io/Xi4IgGVgmOmt+vDGtZg==,type:str]
    apns:
        team_id: ""
        key_id: ""
    host: ENC[AES256_GCM,data:ibTQS05lzf79eESeMvjW7tcO74xc+Q==,iv:wYrxJWU3SWyD3YQnwQ3K+A5TMxQKzndKUFsF1cxfnC0=,tag:nVPaRWpVhBM258IKjKwpZg==,type:str]
image_credentials:
    registry: ENC[AES256_GCM,data:FXHRbUaP4w==,iv:u9I7F23V7gNMWsM31rP6QBno5X16c5tvMDP7OoWBhQk=,tag:+PM1d4dlsal4KzqIAA2ybg==,type:str]
    username: ENC[AES256_GCM,data:7h8IE8pb,iv:vs9v6Bn0h3POYfPTHNyFEzmmgBQ9pO6k7YiPc1YEph0=,tag:osGOpyxdkQsLg9fKpFsEKA==,type:str]
    password: ENC[AES256_GCM,data:gHk34IfZobBybuFSQhHw7aLv0FbI1TeK+RK2sIse0gIICNAZ+0s+QA==,iv:ujJFa5jXQPBBTijH20uJEKfIqE5DsjOcHf79Kbt0cgc=,tag:yPy47cGHos0P+3Waw33YJQ==,type:str]
grafana:
    adminPassword: ENC[AES256_GCM,data:ZeRv6+i5GqETqkmmusBrUY6Ht1c=,iv:clCzPi6EFBNFH+viOQ8NSw62L8v2Q8q2qjrHS0vEQc4=,tag:5uWcrsx90ELrvRmfLY/Tcg==,type:str]
sops:
    age:
        - recipient: age1l8t7aweckzrjkaxj998n0th5wvp6kmzjpcazt770uupe67cvhscqnpahda
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6a1cxS3hLVkFvOVhSUDQ5
            SStseGZnQWZGNUZESlllYlpKOEdJUnRUTTA0CjFLWHMvTnBYM2R2VmljajRlN0h2
            TngxMjJHNGpqeURMdXUwb1NRUGZ2OGcKLS0tICtaWXA0eEdQUndPcVVGMTRCRGk2
            d2dGcGlkc0lLNS95QkxXd3dydHZ2Nm8KycBkJ8eQNPMP5QHSe1ZzPYnFpYbJtV3P
            bwpTBC6kkLuRfCv2KPoF951ZIZZ1k+GXEPu9W20JV2wfTQx+QkG45w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-16T21:26:24Z"
    mac: ENC[AES256_GCM,data:HtI7HE3pVVXImlvexmpPtdr+QhDQ7QbCIm3A1+EhoBUY7XNIr6qR0gNKfYvfoccyUYw8PLWaugcdoiGndXKKuP/gWQVbDnhmdYZgyj+78uoPRvAE7NwHPTDrZYCYoNPv0y3ayIs2F25M7GYzy7k+EK64ErwGBRPqy2hVFA6Wi/c=,iv:7fTtQEyjJESxcO6jVDzmr8Hg5w7r4VIo9R9Eh3LdC8I=,tag:DCAnLIgArQvKvBTuIDxEOg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
