environments:
  dev:
    secrets:
      - "config/secrets-dev.yaml"
  prod:
    secrets:
      - "config/secrets-prod.yaml"

---

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: incubator
    url: https://charts.helm.sh/incubator

helmDefaults:
  kubeContext: coin-1

templates:
  default:
    createNamespace: true
    missingFileHandler: Warn
    namespace: "{{ .Release.Name }}-{{ .Environment.Name }}"
    values:
      - "config/{{ .Release.Name }}/values.yaml.gotmpl"
      - "config/{{ .Release.Name }}/values-{{ .Environment.Name }}.yaml.gotmpl"

releases:
  # Nginx ingresss
  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    namespace: ingress-nginx
    inherit:
      - template: default
    values:
      - controller:
          # 1. Самое важное: разрешаем поду использовать сеть хоста
          hostNetwork: true

          # 2. Указываем, что контроллер должен развернуться как DaemonSet
          # (по одному на каждую ноду), чтобы 80 порт был открыт везде
          kind: DaemonSet

          # 3. Настраиваем политику трафика, чтобы сохранять реальные IP адреса
          externalTrafficPolicy: Local

          # 4. Отключаем тип LoadBalancer, так как мы сидим на HostNetwork
          service:
            type: ClusterIP

          # 5. (Опционально) Если порты 80/443 на хосте заняты чем-то другим,
          # можно их переопределить здесь, но обычно оставляют стандартные.
          dnsPolicy: ClusterFirstWithHostNet

  # Cert-manager
  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    createNamespace: true
    values:
      - crds:
          enabled: true

  - name: letsencrypt-issuer
    chart: incubator/raw
    namespace: cert-manager
    version: 0.2.5
    needs: [cert-manager]
    values:
      - resources:
        - apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: letsencrypt
          spec:
            acme:
              email: bonavii@icloud.com
              server: https://acme-v02.api.letsencrypt.org/directory
              privateKeySecretRef:
                name: letsencrypt-cert
              solvers:
              - http01:
                  ingress:
                    class: nginx

  # Postgresql
  - name: postgres
    chart: bitnami/postgresql
    version: 18.3.0
    inherit:
      - template: default

  # User application Coin
  - name: coin-server
    chart: ./coin-server
    namespace: coin-{{ .Environment.Name }}
    missingFileHandler: Warn
    values:
      - "config/{{ .Release.Name }}/values.yaml.gotmpl" # Дефолтные переменные уровня GitOps
      - "config/{{ .Release.Name }}/values-{{ .Environment.Name }}.yaml.gotmpl" # Environment-ориентированные переменные уровня GitOps
      - "../../{{ .Release.Name }}/deploy/values.local.yaml" # Значения из сервиса при деплое
