environments:
  dev:
    secrets:
      - "config/secrets-dev.yaml"
  prod:
    secrets:
      - "config/secrets-prod.yaml"

---

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

helmDefaults:
  kubeContext: k3s

templates:
  default:
    createNamespace: true
    missingFileHandler: Warn
    namespace: "{{ .Release.Name }}-{{ .Environment.Name }}"
    values:
      - "config/{{ .Release.Name }}/values.yaml.gotmpl"
      - "config/{{ .Release.Name }}/values-{{ .Environment.Name }}.yaml.gotmpl"

releases:
  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    inherit:
      - template: default
    values:
      - controller:
          # 1. Самое важное: разрешаем поду использовать сеть хоста
          hostNetwork: true

          # 2. Указываем, что контроллер должен развернуться как DaemonSet
          # (по одному на каждую ноду), чтобы 80 порт был открыт везде
          kind: DaemonSet

          # 3. Настраиваем политику трафика, чтобы сохранять реальные IP адреса
          externalTrafficPolicy: Local

          # 4. Отключаем тип LoadBalancer, так как мы сидим на HostNetwork
          service:
            type: ClusterIP

          # 5. (Опционально) Если порты 80/443 на хосте заняты чем-то другим,
          # можно их переопределить здесь, но обычно оставляют стандартные.
          dnsPolicy: ClusterFirstWithHostNet

  - name: postgres
    chart: bitnami/postgresql
    version: 18.3.0
    inherit:
      - template: default

  - name: coin-server
    chart: ./coin-server
    namespace: coin-prod
    missingFileHandler: Warn
    values:
      - "config/{{ .Release.Name }}/values.yaml.gotmpl" # Дефолтные переменные уровня GitOps
      - "config/{{ .Release.Name }}/values-{{ .Environment.Name }}.yaml.gotmpl" # Environment-ориентированные переменные уровня GitOps
      - "../../{{ .Release.Name }}/deploy/values.local.yaml" # Значения из сервиса при деплое
